Implemented DELETE /api/v1/observer endpoint in observers list.
code4romania/monitorizare-vot-ong pull request #297
Opened 2020-10-31 14:35 UTC by VladCuciureanu

### What does it fix?

Closes #293

Implements the logic behind the Delete button in the observer list item dropdown.
Uses 'DELETE ​/api​/v1​/observer' endpoint.

### How has it been tested?

Tested manually using local environment configs.

2020-10-31 20:01 UTC, idormenco requested changes

2020-10-31 20:01 UTC, idormenco commented on src/app/components/observers/observers.component.ts
> +    if (confirm('Are you sure you want to remove this observer?')) {
can we use translation service for this message (also other bellow )

2020-10-31 20:01 UTC, idormenco commented on src/app/components/observers/observers.component.ts
> +          this.toastrService.warning('Success', 'Observer has been removed');
this one too

2020-10-31 21:19 UTC, idormenco approved these changes
Looks good to me

2020-10-31 21:23 UTC, VladCuciureanu commented
> Looks good to me

Sorry! I added the localized strings to a previous implementation of the same dialog. You might have to approve the pull request again 😅

2020-10-31 21:28 UTC, idormenco approved these changes

2020-11-03 19:20 UTC, aniri approved these changes

2020-11-03 19:21 UTC, merged