#215 country view list completed
code4romania/monitorizare-vot-ong pull request #354
Opened 2021-10-23 15:03 UTC by Botosio

### #215 
New Polling Station List to View

Closes #215

### How has it been tested?

Tested locally the get and filter options: screen shots below
![image](https://user-images.githubusercontent.com/44526601/138561635-19eaa381-3ac9-4370-a967-3b26a42b37b1.png)

All items in QA
![image](https://user-images.githubusercontent.com/44526601/138561714-27bdc16c-6e8e-48a1-a77f-d1936e74d4fe.png)

TODO:
Asking for new Requirement on table actions.
Buttons on top (import/export/new) are a part of a different requirement.

@aniri

2021-10-23 15:04 UTC, Botosio commented
No polling stations example.
![image](https://user-images.githubusercontent.com/44526601/138561692-ed45a2fd-1d00-4321-b213-8734255c2af1.png)

2021-10-23 16:05 UTC, aniri commented
@Botosio the new page looks great 🚀  

There's a small problem though: the counties dropdown from the answers page is not loading properly:
![image](https://user-images.githubusercontent.com/1358055/138563485-c91a8d24-b3dc-477d-9a6d-06a041ee25cb.png)

Also, if you have the time, could you please make sure that "county" is used instead of "country". I see we have both terms now 😞

2021-10-23 16:22 UTC, Botosio commented
I'll double check that

2021-10-24 21:08 UTC, Botosio commented
This should be fixed now.

2021-10-26 06:32 UTC, idormenco requested changes

2021-10-26 06:32 UTC, idormenco commented on src/app/answers/answers/answers.component.ts
> +  /* counties$: Observable<Partial<County>[]> = this.store.select(getCounties).pipe(
remove commented code

2021-10-26 06:32 UTC, idormenco commented on src/app/answers/answers/answers.component.ts
>      // TODO: call proper API
is this todo still relevant?

2021-10-26 06:32 UTC, idormenco commented on src/app/components/polling-stations/polling-stations.component.html
> +                    <span style="padding-left: 10px">{{ "FORM_PUBLISH" | translate }}</span>
remover commented code

2021-10-26 06:32 UTC, idormenco commented on src/app/components/polling-stations/polling-stations.component.html
> +<div class="row">
remove

2021-10-26 06:32 UTC, idormenco commented on src/app/store/county/county.effects.ts
> +    // withLatestFrom(this.store.select(getCounties)),
remove

2021-10-26 09:01 UTC, Botosio commented on src/app/answers/answers/answers.component.ts
>      // TODO: call proper API
Not sure, doesn't look like the sort works.

![image](https://user-images.githubusercontent.com/44526601/138846255-82218338-c838-425f-b3ef-4c389c83acfc.png)

2021-10-26 09:02 UTC, Botosio commented on src/app/store/county/county.effects.ts
> +    // withLatestFrom(this.store.select(getCounties)),
Done

2021-10-26 09:03 UTC, Botosio commented on src/app/components/polling-stations/polling-stations.component.html
> +<div class="row">
Done

2021-10-26 09:03 UTC, Botosio commented on src/app/components/polling-stations/polling-stations.component.html
> +                    <span style="padding-left: 10px">{{ "FORM_PUBLISH" | translate }}</span>
Done

2021-10-26 09:03 UTC, Botosio commented on src/app/answers/answers/answers.component.ts
> +  /* counties$: Observable<Partial<County>[]> = this.store.select(getCounties).pipe(
Done

2021-10-26 09:04 UTC, Botosio commented on src/app/answers/answers/answers.component.ts
> +  /* counties$: Observable<Partial<County>[]> = this.store.select(getCounties).pipe(
Done

2021-10-27 08:48 UTC, idormenco approved these changes
lgtm

2021-10-27 15:33 UTC, merged